title: Aspia Remote Desktop
author: Dmitry Chapyshev
#email: "dmitry@aspia.ru"
description: >- # this means to ignore newlines until "baseurl:"
  Free open source application for real-time desktop remote control.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Social
#stackoverflow_id:
#twitter_username:
#linkedin_username:
github_username: dchapyshev

repository: "dchapyshev/dchapyshev.github.io"

# kramdown or GFM
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

show_subscribe_cta: True
show_social_icons: True

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# A list of the pages to display in the navigation bar
header_pages:
  - documentation.md
  - donate.md
  - contacts.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
