title: Aspia Remote Desktop
author: Dmitry Chapyshev
description: >- # this means to ignore newlines until "baseurl:"
  Open source application for real-time desktop remote control and file transfer. Aspia supports many features: NAT traversal, system information, audio, chat.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Social
github_username: dchapyshev

repository: "dchapyshev/dchapyshev.github.io"

# kramdown or GFM
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# A list of the pages to display in the navigation bar
header_pages:
  - documentation.md
  - donate.md
  - contacts.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
